FROM jenkins/jenkins:lts

USER root

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    docker.io \
    nodejs \
    npm \
    zip \
    curl \
    git \
    && npm install -g newman \
    && rm -rf /var/lib/apt/lists/*

USER jenkins